application/client/application/asset/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
import requests, json, json
from flask_login import current_user, login_required
from application import API_SERVER, header_info
from application.forms import AdvancedSearchForm

asset = Blueprint('asset', __name__)

# Route: home page
@asset.route("/")
@asset.route("/index")
@login_required
def index():
	if current_user.orgname == 'Org1':
		return redirect(url_for('grower.all'))
	elif current_user.orgname == 'Org2':
		return redirect(url_for('cultivator.all'))
	elif current_user.orgname == 'Org3':
		return redirect(url_for('supplier.all'))
	else:
		return redirect(url_for('users.register'))
		
# Route: history page
@asset.route("/assets/<string:asset_id>/history")
@login_required
def history(asset_id):
	headers = header_info(current_user.token)
	response = requests.get(f'{API_SERVER}/assets/{asset_id}/history', headers=headers) 
	transactions = response.json()
	return render_template(f'history.html', title=f"History for {asset_id}", asset_id=asset_id, transactions=transactions)

# Route: inject
@asset.route("/assets/<string:asset_id>/update/vaccination")
@login_required
def update_vaccination(asset_id):
	headers = header_info(current_user.token)
	response = requests.put(f'{API_SERVER}/assets/{asset_id}/update/vaccination', headers=headers) 
	transactions = response.json()
	flash(transactions['response'], "success")
	return redirect(url_for('grower.health_monitor'))
	# return render_template('transaction.html', title=f"Inject cage - {asset_id}", asset_id=asset_id, transactions=transactions)

# Route: changeage
@asset.route("/assets/<string:asset_id>/update/age")
@login_required
def update_age(asset_id):
	headers = header_info(current_user.token)
	response = requests.put(f'{API_SERVER}/assets/{asset_id}/update/age', headers=headers) 
	transactions = response.json()
	print(transactions)
	if response.status_code != 200:
		flash(transactions['error'], "error")
		return redirect(url_for('grower.all'))
	flash(transactions['response'], 'success')
	return redirect(url_for('grower.all'))
	# return render_template('transaction.html', title=f"Change age - {asset_id}", asset_id=asset_id, transactions=transactions)

# Route: delete
@asset.route("/assets/<string:asset_id>/delete")
@login_required
def delete(asset_id):
	headers = header_info(current_user.token)
	response = requests.delete(f'{API_SERVER}/assets/{asset_id}/delete', headers=headers) 
	if response.status_code != 200:
		flash('Cage not found', "warning")
		return redirect(url_for('grower.all'))
	transactions = response.json()
	flash(transactions['response'], "success")
	return redirect(url_for('grower.all'))
	# return render_template('transaction.html', title=f"Deleted - {asset_id}", asset_id=asset_id, transactions=transactions)

# Route: edit asset
@asset.route("/assets/<string:asset_id>/edit", methods=["POST", "GET"])
@login_required
def edit(asset_id):
	headers = header_info(current_user.token)
	if request.method == "POST":
		quantity = request.form.get('quantity', 0)
		product_serial = request.form.get('product_serial', 'NaN')
		message = request.form.get('message', 'Default')

		req = {
			'quantity': f'{quantity}',
			'product_serial': f'{product_serial}',
			'message': f'{message}'
			}
		req = json.loads(json.dumps(req))
		# print(req)

		response = requests.put(f'{API_SERVER}/assets/{asset_id}/edit', json=req, headers=headers)
		
		# check for error
		if response.status_code != 200:
			flash('Something went wrong, please try later!', "error")
			return redirect(url_for('grower.all'))
		
		transactions = response.json()
		flash("Updated successfully", "success")
		return redirect(url_for('grower.all', asset_id=asset_id))
		# return render_template(f'edit.html', title=f"Data - {asset_id}", asset_id=asset_id, transactions=transactions)
	else:
		response = requests.get(f'{API_SERVER}/assets/{asset_id}', headers=headers) 
		
		# check for error
		if response.status_code != 200:
			flash("Asset not found", "error")
			return redirect(url_for('grower.all'))

		transactions = response.json()
		return render_template(f'edit.html', title=f"Edit - {asset_id}", asset_id=asset_id, transactions=transactions)

# Route: create cage
@asset.route("/assets/search/", methods=["POST", "GET"])
@login_required
def search():
	headers = header_info(current_user.token)
	form = AdvancedSearchForm()
	if form.validate_on_submit():
		product_serial = form.product_serial.data
		flag = form.flag.data

		req = {
			'product_serial': f'{product_serial}',
			'flag': f'{flag}'
			}
		req = json.loads(json.dumps(req))
		# send the data
		response = requests.get(f'{API_SERVER}/assets/search/0/', json=req, headers=headers) 
		if response.status_code != 200:
			flash(req, "error")
			return redirect(url_for('asset.search'))
		transactions = response.json()
		if len(transactions['data']) == 0:
			return render_template('empty_list.html', title="Advanced search results", text="Nothing found")
		flash("Founded results", "success")
		return render_template('assets.html', title="Advanced search results", transactions=transactions)
	return render_template('search.html', title="Advanced search", form=form)

application/client/application/supplier/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
import requests, json, json
from flask_login import current_user, login_required
from application import API_SERVER, header_info
from application.forms import DeliveryInfoForm
from application.utils import generate_QR

# QR code library+
import qrcode
from PIL import Image

supplier = Blueprint('supplier', __name__)

# Route: request to delivery organization
@supplier.route("/supplier/<string:asset_id>/request")
@login_required
def request(asset_id):
	headers = header_info(current_user.token)
	req = {
		'flag': 'SR'
	}
	req = json.loads(json.dumps(req))
	response = requests.put(f'{API_SERVER}/assets/{asset_id}/start-next-phase', json=req, headers=headers) 
	# print(response)
	if response.status_code != 200:
		flash("Error occured, please ask from back-end team", "error")
		return redirect(url_for('cultivator.all'))
	flash("Asset is added to waiting list. Supplier organization must confirm to proceed.", "success")
	return redirect(url_for('cultivator.all'))

# Route: show all processing plant data
@supplier.route("/supplier/all")
@supplier.route("/supplier/all/<string:bookmark>")
@login_required
def all(bookmark=0):
	headers = header_info(current_user.token)
	response = requests.get(f'{API_SERVER}/supplier/assets/all/{bookmark}', headers=headers) 
	if response.status_code != 200:
		flash("Something went wrong (", "error")
		return render_template('empty_list.html', title="Supplier", text="Nothing found")
	transactions = response.json()
	if len(transactions['data']) == 0:
		return render_template('empty_list.html', title="Supplier", text="Nothing found")
	return render_template('supplier_menu.html', title="Supplier - current state", bookmark=bookmark, transactions=transactions)

# Route: show all processing plant data
@supplier.route("/supplier/finished")
@supplier.route("/supplier/finished/<string:bookmark>")
@login_required
def finished(bookmark=0):
	headers = header_info(current_user.token)
	response = requests.get(f'{API_SERVER}/supplier/assets/finished/{bookmark}', headers=headers) 
	if response.status_code != 200:
		flash("Error occured, please ask from back-end team", "error")
		return render_template('empty_list.html', title="Supplier", text="Nothing found")
	transactions = response.json()
	if len(transactions['data']) == 0:
		return render_template('empty_list.html', title="Supplier - finished products", text="Finished products not found")
	return render_template('supplier_menu.html', title="Supplier - finished products", page="finished", bookmark=bookmark, transactions=transactions)

# Route: show all processing plant data - confirmation
@supplier.route("/supplier/confirmation")
@supplier.route("/supplier/confirmation/<string:bookmark>")
@login_required
def confirmation(bookmark=0):
	headers = header_info(current_user.token)
	response = requests.get(f'{API_SERVER}/supplier/assets/confirmation/{bookmark}', headers=headers) 
	if response.status_code != 200:
		flash("Something went wrong (", "error")
		return render_template('empty_list.html', title="Supplier", text="Nothing found")
	transactions = response.json()
	if len(transactions['data']) == 0:
		return render_template('empty_list.html', title="Supplier", text="Nothing found")
	return render_template('supplier_menu.html', title="Supplier - confirmation", page="confirmation", bookmark=bookmark, transactions=transactions)

# Route: processing plant - start
@supplier.route("/supplier/<string:asset_id>/start", methods=["POST", "GET"])
@login_required
def start(asset_id):
	headers = header_info(current_user.token)
	form  = DeliveryInfoForm()
	if form.validate_on_submit():
		plate_number = form.plate_number.data
		message = form.message.data

		if (plate_number is None or message is None):
			flash('Please enter all required fields!')
			return redirect(url_for('cultivator.start', asset_id=asset_id))
		req = {
			'plate_number': f'{plate_number}',
			'message': f'{message}'
			}
		req = json.loads(json.dumps(req))
		
		response = requests.put(f'{API_SERVER}/supplier/{asset_id}/start', json=req, headers=headers)
		
		# check for error
		if response.status_code != 200:
			flash("Error occured during the transaction, please contact with back-end team", "error")
			return redirect(url_for('supplier.all'))
		
		transactions = response.json()
		flash("Updated successfully", "success")
		return redirect(url_for('supplier.all', asset_id=asset_id))
		# return render_template(f'delivery_process.html', title=f"Supplier - {asset_id}", asset_id=asset_id, transactions=transactions)
	else:
		response = requests.get(f'{API_SERVER}/assets/{asset_id}', headers=headers) 
		
		# check for error
		if response.status_code != 200:
			flash("Asset not found", "error")
			return redirect(url_for('supplier.confirmation', asset_id=asset_id))
		transactions = response.json()
		return render_template(f'delivery_info.html', title=f"Supplier - {asset_id}", asset_id=asset_id, form=form, flag='SR', transactions=transactions)

# Route: processing plant - finish
@supplier.route("/supplier/<string:asset_id>/finish", methods=["GET"])
@login_required
def finish(asset_id):
	headers = header_info(current_user.token)

	response = requests.put(f'{API_SERVER}/supplier/{asset_id}/finish', headers=headers)
	
	# check for error
	if response.status_code != 200:
		flash("Error occured during the transaction, please contact with back-end team", "error")
		return redirect(url_for('supplier.all'))
	
	# transactions = response.json()
	flash("Updated successfully", "success")
	return redirect(url_for('supplier.finished', asset_id=asset_id))


# Route: generate QR code page
@supplier.route("/supplier/<string:asset_id>/generate-qr-code")
@login_required
def generate_qr(asset_id):
	file_path = generate_QR(asset_id)
	print(file_path)
	return render_template('qr_code.html', title=f'QR code - {asset_id}', file=f'qr-codes/{asset_id}.png')

application/client/application/users/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint, request
from application import  db, bcrpyt, API_SERVER
from flask_login import current_user, login_user, logout_user, login_required
from application.models import User
from application.forms import RegistirationForm, LoginForm, UpdateAccountForm
from application.utils import save_file
import json, requests

users = Blueprint('users', __name__)

# Route: login page
@users.route("/login", methods=["POST", "GET"])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('asset.index'))
	form  = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrpyt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=True)
			req = {
				'email': f'{user.email}',
				'orgname': f'{user.orgname}'
			}
			req = json.loads(json.dumps(req))
			# send the data to get new token
			response_back = requests.post(f'{API_SERVER}/users/login', json=req)
			response = response_back.json()
			print(response)
			if response_back.status_code != 200:
				flash(req, "error")
				return redirect(url_for('users.register'))
			if response['success']:
				flash(response['message'], "success")
				user.token = response['token']
				db.session.commit()
				# next_page = request.args.get('next')
				if user.orgname == 'Org1':
					return redirect(url_for('grower.all'));
				elif user.orgname == 'Org2':
					return redirect(url_for('cultivator.all'));
				elif user.orgname == 'Org3':
					return redirect(url_for('supplier.all'));
				else:
					return redirect(url_for('users.register'));
				# return redirect(next_page) if next_page else redirect(url_for('asset.index'))
			else:
				flash(response['message'], "error")
			return redirect(url_for('users.login'))
		else:
			flash('Login Unsuccessful. Please check email and password', 'danger')
	return render_template('login.html', title="Login", form=form)

# Route: registeration page
@users.route("/register", methods=["POST", "GET"])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('asset.index'))
	form = RegistirationForm()
	if form.validate_on_submit():
		req = {
			'email': f'{form.email.data}',
			'orgname': f'{form.orgname.data}'
		}
		req = json.loads(json.dumps(req))
		print(req)
		# send the data
		response = requests.post(f'{API_SERVER}/users/register', json=req) 
		if response.status_code != 200:
			flash("Something went wrong, please try again (", "error")
			return redirect(url_for('users.register'))
		response = response.json()
		if response['success']:
			hashed_password = bcrpyt.generate_password_hash(form.password.data).decode('utf-8')
			user = User(email=form.email.data, orgname=form.orgname.data, password=hashed_password)
			db.session.add(user)
			db.session.commit()
			flash('Your account has been created, please log in!', 'success')
			return redirect(url_for('users.login'))
		else:
			flash(response['message'], "error")
	return render_template('register.html', title='Registration', form=form)

# Route: Logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route("/profile")
@users.route("/profile/<string:email>")
@login_required
def profile(email=None):
	if (email is None):
		image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
		return render_template('profile.html', title='My profile', user=current_user, image_file=image_file)
	user = User.query.filter_by(email=email).first()
	if (user is None):
		return render_template('empty_list.html', title='Account not found', text='Account not found!')
	image_file = url_for('static', filename='profile_pics/' + user.image_file)
	return render_template('profile.html', title=f'Profile - {email}', user=user, image_file=image_file)
	
	

@users.route("/update-profile", methods=['POST', 'GET'])
@login_required
def update_profile():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_file(form.picture.data)
            current_user.image_file = picture_file
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.location = form.location.data
        current_user.phone = form.phone.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.update_profile'))
    elif request.method == 'GET':
        form.email.data = current_user.email
        if (current_user.first_name): form.first_name.data = current_user.first_name
        if (current_user.last_name): form.last_name.data = current_user.last_name
        if (current_user.location): form.location.data = current_user.location
        if (current_user.phone): form.phone.data = current_user.phone
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('update_profile.html', title='Edit ptofile', image_file=image_file, form=form)

application/client/application/templates/create_cage.html
{% extends 'base.html' %}
{% block content %}
  <div class="create">
    <!-- START FORM -->
      <div class="row">
        <form class="col s12" action="create_cage" method="POST">
            <div class="row">
              <div class="input-field col s6">
                <input placeholder="ID" name="id" type="text" >
              </div>
              <div class="input-field col s6">
                <input placeholder="Age" name="age" type="text" >
              </div>
              <div class="row">
                </div><div class="switch col">
                  <label>
                    False
                    <input type="checkbox" name="vaccination">
                    <span class="lever"></span>
                    True
                  </label>
                </div>
              </div>
            </div>
            <input class="waves-light btn our-colour" type="submit" value="Submit" name="">
            <!-- <input  onclick="location.href='/changeOwner/wholesaler';" class="waves-light btn our-colour" type="button" value="Transfer Ownership" style="color: white;"  name=""> -->
        </form>
      </div>
    <!-- END FORM -->
  </div>
{% endblock %}

application/client/application/templates/delivery_info.html
{% extends 'base.html' %}
{% block content %}
<div class="create" style="padding: 10px;">
  <div class="row">
    {% if flag == 'CR' %}
    <form class="col s12" action="{{ url_for('cultivator.start', asset_id=asset_id) }}" method="POST">
      {% else %}
      <form class="col s12" action="{{ url_for('supplier.start', asset_id=asset_id) }}" method="POST">
        {% endif %}
        {{ form.hidden_tag() }}
        <div class="row">
          <!-- <div class="input-field col s12"> -->
          <!-- <i class="material-icons prefix">play_arrow</i> -->
          {% if form.plate_number.errors %}
            {{ form.plate_number(placeholder="Plate number") }}
          <div class="invalid-feedback">
            {% for error in form.plate_number.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
            {{ form.plate_number(placeholder="Plate number") }}
          {% endif %}
        </div>
        <!-- <div class="input-field col s12">
          <input id="icon_prefix2" name="quantity" value="" type="text" class="validate">
          <label for="icon_prefix2">Product serial</label>
      </div> -->
        <div class="row">
          <!-- <i class="material-icons prefix">play_arrow</i> -->
          {% if form.message.errors %}
            {{ form.message(placeholder="Label info") }}
          <div class="invalid-feedback">
            {% for error in form.message.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
            {{ form.message(placeholder="Label info") }}
          {% endif %}
        </div>
        <div class="row">{{ form.submit(class="btn btn-outline-info") }}</div>
      </form>
  </div>
  {% endblock %}

application/client/application/templates/delivery_pages.html
{% extends 'base.html' %}
{% block content %}
  <div class="transactions">
    <!-- START TABLE -->
    <table class="highlight centered responsive-table">
        {% if page == 'finished' %}
          <thead>
            <tr>
              <th>ID</th>
              <th>Deliverer</th>
              <th>Address</th>
              <th>Status</th>
              <!-- <th>Start Delivery</th> -->
            </tr>
          </thead>
          <tbody>
            {% for arr in transactions['data'] %}
            <tr>
              <td style="text-transform:uppercase;">
                <a class="waves-effect waves-light btn" href="{{ url_for('asset.history', asset_id=arr['key'])}}" title="See history">{{ arr['key'] }}</a>
              </td>
              <td>{{ arr['data']['supplier']['delivery']['deliverer'] }}</td>
              <td>{{ arr['data']['supplier']['delivery']['message'] }}</td>
              <td>{{ arr['data']['supplier']['status'] }}</td>
              <!-- <td>
                <a href="{{ url_for('supplier.request', asset_id=arr['key']) }}" title="Confirm"><i class="material-icons md-30">&nbsp;next_plan</i></a>
              </td> -->
            </tr>
            {% endfor %}
          </tbody>
        {% elif page == 'confirmation' %}
          <thead>
            <tr>
              <th>ID</th>
              <th>Status</th>
              <th>Confirm</th>
            </tr>
          </thead>
          <tbody>
            {% for arr in transactions['data'] %}
            <tr>
              <td style="text-transform:uppercase;">
                <a class="waves-effect waves-light btn" href="{{ url_for('asset.history', asset_id=arr['key'])}}" title="See history">{{ arr['key'] }}</a>
              </td>
              <!-- <td>
                <a href="{{ url_for('supplier.request', asset_id=arr['key']) }}" title="Confirm"><i class="material-icons md-30">&nbsp;next_plan</i></a>
              </td> -->
              <td>{{ arr['data']['supplier']['status'] }}</td>
              <td>
                <a href="{{ url_for('supplier.start', asset_id=arr['key']) }}" title="Confirm"><i class="material-icons md-30">&nbsp;check_box</i></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        {% else %}
          <thead>
            <tr>
              <th>ID</th>
              <th>Deliverer</th>
              <th>Message</th>
              <th>Stage</th>
              <th>QR code</th>
              <th>Update</th>
          </tr>
          </thead>
          <tbody>
            {% for arr in transactions['data'] %}
            <tr>
              <td style="text-transform:uppercase;">
                <a class="waves-effect waves-light btn" href="{{ url_for('asset.history', asset_id=arr['key'])}}" title="See history">{{ arr['key'] }}</a>
              </td>
              <td>
                {% if arr['data']['supplier']['delivery']['deliverer'] is defined %}
                  {{ arr['data']['supplier']['delivery']['deliverer'] }}
                {% else %}
                  -
                {% endif %}
              </td>
              <td>
                {% if arr['data']['supplier']['delivery']['message'] is defined %}
                  {{ arr['data']['supplier']['delivery']['message'] }}
                {% else %}
                  -
                {% endif %}
              </td>
              <td>{{ arr['data']['supplier']['status'] }}</td>
              <td><a href="{{ url_for('supplier.generate_qr', asset_id=arr['key']) }}" title="QR code generator"><i class="material-icons md-30">&nbsp;add</i></a></td>
              <td><a href="{{ url_for('supplier.start', asset_id=arr['key']) }}" title="Update"><i class="material-icons md-30">&nbsp;autorenew</i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        {% endif %}
    </table>
    <!-- END TABLE -->
  </div>

  <br />
    <ul class="pagination col center-align">
      {% if bookmark != 0 %}
        <li class="waves-effect">
          <a href="javascript:history.go(-1)">
            <i class="material-icons">chevron_left</i>
          </a>
        </li>
      {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
      {% endif %}
      {% if transactions['meta_data']['fetchedRecordsCount'] >= 10 %}
        <li class="waves-effect">
          {% if page == 'finished' %}
            <a href="{{ url_for('supplier.finished', bookmark=transactions['meta_data']['bookmark']) }}">
              <i class="material-icons">chevron_right</i>
            </a>
          {% elif page == 'confirmation' %}
            <a href="{{ url_for('supplier.confirmation', bookmark=transactions['meta_data']['bookmark']) }}">
              <i class="material-icons">chevron_right</i>
            </a>
          {% else %}
            <a href="{{ url_for('supplier.all', bookmark=transactions['meta_data']['bookmark']) }}">
              <i class="material-icons">chevron_right</i>
            </a>
          {% endif %}
        </li>
      {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
      {% endif %}
    </ul>
{% endblock %}

application/client/application/templates/processing_plant_pages.html
{% extends 'base.html' %}
{% block content %}
  <div class="transactions">
    <!-- START TABLE -->
    <table class="highlight centered responsive-table">
        {% if page == 'finished' %}
          <thead>
            <tr>
              <th>ID</th>
              <th>Status</th>
              <th>Inspection</th>
              <th>Timestamp</th>
              <!-- <th>Start Delivery</th> -->
            </tr>
          </thead>
          <tbody>
            {% for arr in transactions['data'] %}
            <tr>
              <td style="text-transform:uppercase;">
                <a class="waves-effect waves-light btn" href="{{ url_for('asset.history', asset_id=arr['key'])}}" title="See history">{{ arr['key'] }}</a>
              </td>
              <td>{{ arr['data']['cultivator']['status'] }}</td>
              <td>{{ arr['data']['cultivator']['delivery']['deliverer'] }}</td>
              <td>{{ daysCount(arr['data']['cultivator']['delivery']['timestamp']) }}</td>
              <!-- <td>
                <a href="{{ url_for('supplier.request', asset_id=arr['key']) }}" title="Confirm"><i class="material-icons md-30">&nbsp;next_plan</i></a>
              </td> -->
            </tr>
            {% endfor %}
          </tbody>
        {% elif page == 'confirmation' %}
          <thead>
            <tr>
              <th width="20%">ID</th>
              <th>Status</th>
              <th>Confirm</th>
            </tr>
          </thead>
          <tbody>
            {% for arr in transactions['data'] %}
            <tr>
              <td style="text-transform:uppercase;">
                <a class="waves-effect waves-light btn" href="{{ url_for('asset.history', asset_id=arr['key'])}}" title="See history">{{ arr['key'] }}</a>
              </td>
              <!-- <td>
                <a href="{{ url_for('supplier.request', asset_id=arr['key']) }}" title="Confirm"><i class="material-icons md-30">&nbsp;next_plan</i></a>
              </td> -->
              <td>{{ arr['data']['cultivator']['status'] }}</td>
              <td>
                <a href="{{ url_for('cultivator.start', asset_id=arr['key']) }}" title="Confirm"><i class="material-icons md-30">&nbsp;check_box</i></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        {% else %}
          <thead>
            <tr>
              <th>ID</th>
              <th>Status</th>
              <th>Serial N</th>
              <th>Nect stage</th>
              <th>Update</th>
          </tr>
          </thead>
          <tbody>
            {% for arr in transactions['data'] %}
            <tr>
              <td style="text-transform:uppercase;">
                <a class="waves-effect waves-light btn" href="{{ url_for('asset.history', asset_id=arr['key'])}}" title="See history">{{ arr['key'] }}</a>
              </td>
              <td>
                {{ arr['data']['cultivator']['status'] }}
              </td>
              <td>
                {{ arr['data']['product_serial']|upper }}
              </td>
              <!-- <td>{{ daysCount(arr['data']['timestamp']) }}</td> -->
              <td>
                {% if (daysCount(arr['data']['timestamp'], remaining_days=True) < 0)  %}
                  {{ 45 - daysCount(arr['data']['timestamp'], remaining_days=True) }} days left
                {% else %}
                  <a href="{{ url_for('supplier.request', asset_id=arr['key']) }}" title="Update"><i class="material-icons md-30">&nbsp;next_plan</i></a>
                {% endif %}
              </td>
            
              <td><a href="{{ url_for('cultivator.record_medicine', asset_id=arr['key']) }}" title="Delete"><i class="material-icons md-30">&nbsp;autorenew</i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        {% endif %}
    </table>
    <!-- END TABLE -->
  </div>

  <br />
    <ul class="pagination col center-align">
      {% if bookmark != 0 %}
        <li class="waves-effect">
          <a href="javascript:history.go(-1)">
            <i class="material-icons">chevron_left</i>
          </a>
        </li>
      {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
      {% endif %}
      {% if transactions['meta_data']['fetchedRecordsCount'] >= 10 %}
        <li class="waves-effect">
          {% if page == 'finished' %}
            <a href="{{ url_for('cultivator.finished', bookmark=transactions['meta_data']['bookmark']) }}">
              <i class="material-icons">chevron_right</i>
            </a>
          {% elif page == 'confirmation' %}
            <a href="{{ url_for('cultivator.confirmation', bookmark=transactions['meta_data']['bookmark']) }}">
              <i class="material-icons">chevron_right</i>
            </a>
          {% else %}
            <a href="{{ url_for('cultivator.all', bookmark=transactions['meta_data']['bookmark']) }}">
              <i class="material-icons">chevron_right</i>
            </a>
          {% endif %}
        </li>
      {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
      {% endif %}
    </ul>
{% endblock %}

application/client/application/templates/qr_code.html
{% extends 'base.html' %}
{% block content %}
  <div class="create">
      <center>
          <p>{{ title }}</p>
        <img src="{{ url_for('static', filename=file) }}" width="300px" />
      </center>
  </div>
{% endblock %}